name: build-test-deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '20' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        env:
          CYPRESS_INSTALL_BINARY: 0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:coverage

      - name: Build
        if: success()
        run: npm run build:prod

      - name: Upload Codecov
        if: success()
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info
          flags: unittests

      - name: Deploy
        if: success()
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist/gestructureerde-mededeling'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
