name: build-test-deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        env:
          PNPM_HOME: /home/runner/.local/share/pnpm

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Run tests
        run: pnpm run test

      - name: Build
        if: success()
        run: pnpm run build:prod

#      - name: Upload Codecov
#        if: success()
#        uses: codecov/codecov-action@v3
#        with:
#          files: ./coverage/lcov.info
#          flags: unittests

      - name: Deploy
        if: success()
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist/gestructureerde-mededeling/browser'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
